# Use official Oracle Linux slim image
FROM ghcr.io/oracle/oraclelinux8-instantclient:19

RUN yum install dos2unix traceroute \
&& yum clean all

# set the timezone of the linux container to UTC
ENV TZ=UTC

# copy the rest of the backend files:
COPY ./src /usr/src

# convert the shell script to unix line endings
RUN dos2unix /usr/src/*.sh 

# change directory to the SQL source directory
WORKDIR /usr/src

CMD ["bash", "/usr/src/run_db_app_deployment.sh"]

# CMD tail -f /dev/null 